### ISSUE TITLE
instrument_openai don't work with openai 1.76.0 and AsyncOpenAI

### ISSUE THREAD

**Issue by BuT9l3b** [pydantic/logfire#1040]
### Description

I update openai from 1.65.1 to 1.76.0 and got this error. I didn't have these problems before.

```
  File "F:\PycharmProjects\BuT9l3b_AI_Bot\Bot\AI_api.py", line 107, in _create_client
    logfire.instrument_openai(async_client)  # For logfire (optional)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PycharmProjects\BuT9l3b_AI_Bot\venv\Lib\site-packages\logfire\_internal\main.py", line 1140, in instrument_openai
    return instrument_llm_provider(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PycharmProjects\BuT9l3b_AI_Bot\venv\Lib\site-packages\logfire\_internal\integrations\llm_providers\llm_provider.py", line 71, in instrument_llm_provider
    client._original_request_method = original_request_method = client._request
                                                                ^^^^^^^^^^^^^^^
AttributeError: 'AsyncOpenAI' object has no attribute '_request'
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.14.0"
platform="Windows-10-10.0.19045-SP0"
python="3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
openai="1.76.0"
protobuf="5.29.4"
rich="14.0.0"
executing="2.2.0"
opentelemetry-api="1.32.1"
opentelemetry-exporter-otlp-proto-common="1.32.1"
opentelemetry-exporter-otlp-proto-http="1.32.1"
opentelemetry-instrumentation="0.53b1"
opentelemetry-instrumentation-dbapi="0.53b1"
opentelemetry-instrumentation-httpx="0.53b1"
opentelemetry-instrumentation-sqlite3="0.53b1"
opentelemetry-proto="1.32.1"
opentelemetry-sdk="1.32.1"
opentelemetry-semantic-conventions="0.53b1"
opentelemetry-util-http="0.53b1"
```

**Comment by alexmojaki** [comment]
This is fixed in 3.14.1
