### PR TITLE
Match each extra scrubbing pattern independently

### LINKED ISSUE #2237: Numeric backreferences in extra_patterns refer to groups from other patterns, so the pattern silently never matches
> This issue was posted by Claude Code using claude-opus-5 on behalf of David.

### Description

`Scrubber.__init__` joins every pattern into a single alternation, so all patterns share one capture-group numbering space. A numeric backreference in one `extra_patterns` entry therefore refers to a group in an *earlier* entry rather than to its own:

```python
import re
from logfire._internal.scrubbing import Scrubber

Scrubber(['(a)', r'(b)\1']).scrub_value(('attributes', 'x'), 'bb')
# -> 'bb'   (not scrubbed)

re.compile(r'(b)\1').search('bb')
# -> <re.Match object; span=(0, 2), match='bb'>   (the pattern works on its own)
```

In the joined pattern, `(a)` is group 1 and `(b)` is group 2, so the `\1` in the second entry points at `(a)`, which never participated in the match. The pattern silently never matches, so data the user expected to be redacted is exported.

This is long-standing and not specific to any recent change — it reproduces identically on `main`. It only affects users with **two or more** `extra_patterns` where a later one uses a numeric backreference; a single pattern with a backreference works, because the default patterns contain no capture groups.

### Suggested fix

Neither option is free, which is why this is its own issue rather than a drive-by:

- **Match each pattern separately.** Fully isolates numbering, but replaces one `re` call per value with N, on a path that runs during span creation on the application's thread.
- **Rewrite numeric backreferences when joining**, offsetting each by the number of groups already emitted. Keeps the single-pass search, but hand-rewriting regex internals is its own source of bugs.
- **Reject numeric backreferences in `extra_patterns`** with a clear error, pointing at named groups (`(?P<x>...)` / `(?P=x)`), which are unaffected because names aren't renumbered.

The third is the cheapest and turns a silent failure into a loud one, which is the main harm here.

### Versions

Reproduced on `logfire==4.40.0`, Python 3.13.3, macOS. Found by the Macroscope reviewer on #2236.

### PR DESCRIPTION
**Pull request by IgorKasianenko**
Fixes #2237

`Scrubber.__init__` joined every pattern into a single alternation, so all patterns shared one
capture-group numbering space. A numeric backreference in one `extra_patterns` entry referred to a
group in an earlier entry rather than to its own, so the pattern silently never matched and data the
user expected to be redacted was exported.

**What this changes**

Patterns are still combined into one regex wherever that is safe, and only neighbouring patterns are
combined, so the compiled list stays in the configured order. A pattern that contains a capture group
is compiled on its own, which keeps its group numbering to itself, so its groups, backreferences and
conditionals mean what they say.

The condition is a capture group, not a backreference, and it is read from the public
`re.Pattern.groups` attribute. A group is the necessary condition for the bug — there is no
backreference or conditional reference without one — so this needs no parsing of regex source and
rejects nothing that works today. A grouped pattern with no backreference is separated too, which
costs one extra search and changes no behaviour.

Four things are fixed by the same change:

| Configuration | Before | After |
|---|---|---|
| `extra_patterns=['(a)', r'(b)\1']`, value `'q bb'` | not redacted | `[Scrubbed due to 'bb']` |
| `extra_patterns=['(a)', r'(x)?(?(1)y\|z)']`, value `'q xy'` | not redacted | `[Scrubbed due to 'xy']` |
| `extra_patterns=[r'(?P<x>aaa)', r'(?P<x>bbb)']` | `re.error: redefinition of group name 'x' as group 2; was group 1 at position 272` | works |
| `extra_patterns=[r'(?s)fo.o']` | `re.error: global flags not at the start of the expression at position 259` | works |

The last two were loud rather than silent, but the positions in those messages index the combined
pattern, which the user never wrote. Compiling each pattern separately also fixes that: an invalid
pattern now reports `unterminated character set (in scrubbing pattern 'bad[(') at position 3`.

**Performance**

Scrubbing runs on the application's thread during span creation, so the joining is worth keeping.
None of the 18 default patterns contains a capture group, so the default configuration — and any
configuration whose extra patterns have no groups — still compiles to exactly one regex and does
exactly one search per value, as it does today. `SpanScrubber` binds that single pattern's `search`
directly, so there is no added call on the common path.

Scrubbing a span of five attributes, 20k iterations, Python 3.13, three alternating rounds of
`main` and this branch to cancel drift (ranges across rounds):

```
                 main            this branch
default          3.94-3.98 us    4.02-4.15 us
plain extra      4.54-4.56 us    4.59-4.75 us
grouped extra    4.60-4.68 us    4.93-4.98 us
```

A configuration with no capture groups is within a few percent of `main`, close to the noise floor
of this measurement. Only a user who writes a capture group pays the real cost of a second search,
and that is the case that was silently broken.

A test asserts the number of compiled regexes for five configurations, so a later refactor cannot
quietly turn the single search into one per pattern.

**A note on the reproduction in the issue**

The snippet in #2237 still returns `'bb'` after this change, for an unrelated reason: `scrub` treats
a value as safe when the *whole* string matches, so `'bb'` against `(b)\1` is a full match and is
kept, exactly as the value `'password'` is kept today
([`scrubbing.py`](https://github.com/pydantic/logfire/blob/main/logfire/_internal/scrubbing.py#L392-L395)).
Using `'q bb'` shows the real difference. The same confound applies to the conditional-reference
case: with the value `'z'` the joined pattern happens to agree with the standalone one, so `'q xy'`
is used in the test instead.

**Tests**

`tests/test_secret_scrubbing.py` gains 18 cases: five for patterns matched independently, two for
patterns keeping their configured order, two for the callback receiving the right match, two for
error messages naming the pattern, one for a pattern that only warns, five for the number of
compiled regexes, and one end-to-end `logfire.configure` test with a snapshot.

**Checks**

Run in Docker against a clean `origin/main` for comparison:

- `ruff check`, `ruff format --check`, `pyright` — clean.
- Python 3.13: 2310 passed, 5 failed. Python 3.10: 2306 passed, 6 failed. Every failure also fails
  on unmodified `main` in the same image (`main` is 6 failed on 3.13, 7 on 3.10) — they need a
  Docker socket or a subprocess that the container does not have.
- On the host, where those pass: 2325 passed, 9 skipped, 2 xfailed, 0 failed.
- `logfire/_internal/scrubbing.py` is at 100% statement and branch coverage.

**Open question for maintainers**

`docs/how-to-guides/scrubbing.md` describes `extra_patterns` as "a list of regex strings" and says
nothing about capture groups, so I could not find a statement of whether a group in an extra pattern
is meant to work at all. This PR makes it work, which is the reading that rejects nothing users
already have. The alternative in the issue — refusing numeric backreferences with a clear error — is
a smaller change but turns some working patterns into a startup error. Please let me know what is
best product behaviour and what are recommended user flows; I am happy to swap this for the
rejecting version if that is what you want.

Docs changed, so the `trigger:docs` label would be needed for a preview.

**Left out deliberately**

An empty extra pattern (`''`, or an equivalent such as `'a*'`) matches at every position, so every
string value in every span is replaced by `[Scrubbed due to '']`. That is a separate root cause with
its own behaviour question — whether to reject such a pattern at configure time — so I have not
mixed it into this PR. Would you like an issue for it?

### CODE REVIEW

File: logfire/_internal/scrubbing.py [hunk 1]
```diff
@@ -205,13 +209,82 @@ def scrub_value(self, path: JsonPath, value: Any) -> tuple[Any, list[ScrubbedNot
...
+    separate: list[re.Pattern[str]] = []
+    for pattern in extra_patterns or []:
+        compiled = _compile_pattern(pattern)
+        if compiled.groups or not _can_be_joined(pattern):
+            separate.append(compiled)
+        else:
+            joinable.append(pattern)
+    # The separate patterns go last, so when two patterns match at the same position the combined
+    # one wins, as it would have when everything was in a single alternation.
+    return [re.compile('|'.join(joinable), _SCRUBBING_FLAGS), *separate]
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply logfire/_internal/scrubbing.py]: Correct, and the example holds exactly as written. Fixed in the follow-up commit.

Collecting the ungrouped patterns into one list did move them ahead of any grouped pattern configured before them. Checked against `main` rather than reasoned about:

```
extra_patterns=[r'(TOKEN=)', r'TOKEN=.*'], value 'TOKEN=secret'
main            -> [Scrubbed due to 'TOKEN=']
this branch     -> 'TOKEN=secret'      # exported unchanged
```

`TOKEN=.*` ended up inside the combined regex, won at position 0 with a whole-string match, and the whole-string exemption in `scrub` then kept the value. My comment on that line claimed the opposite, and was wrong.

`_compile_patterns` now combines only neighbouring joinable patterns and flushes the batch whenever a pattern needs its own regex, so the compiled list stays in configured order and `_leftmost_match` still resolves a same-position tie to the earliest pattern. Both orderings are pinned by `test_extra_patterns_keep_their_configured_order`, which fails on the previous commit.

On the threat model: the pattern list comes from the application's own `logfire.configure()` call, so an attacker controls the span value, never the ordering. The leak is real either way.

[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply logfire/_internal/scrubbing.py]: Right, and fixed in the follow-up commit — `_compile_patterns` now combines only neighbouring joinable patterns, so the compiled list keeps the configured order.

Verified against `main` rather than reasoned about. Your `['(?P<x>zzz)', 'zzz']` case gave the callback `groupdict()` of `{}` on the previous commit and `{'x': 'zzz'}` on `main`; it now matches `main`. The more serious shape of the same bug is `[r'(TOKEN=)', r'TOKEN=.*']` against `'TOKEN=secret'`, where the promoted `TOKEN=.*` matched the whole value and the whole-string exemption then exported it unredacted. Both are pinned by new tests that fail on the previous commit.

One correction to the proposed diff: as written it clears `joinable` and then joins unconditionally on the next separated pattern, so two adjacent grouped patterns produce `re.compile('')`, which matches at every position and would redact every value in every span. The implementation flushes through a helper that returns early when the batch is empty, and `test_only_patterns_with_groups_need_their_own_regex` covers the adjacent case.

[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply logfire/_internal/scrubbing.py]: Confirmed and fixed in the follow-up commit. `_compile_patterns` now combines only neighbouring joinable patterns, so a pattern that needs its own regex stays where it was configured and a same-position tie still resolves to the earliest pattern.

The whole-string guard was the damaging part, as you say: `[r'(TOKEN=)', r'TOKEN=.*']` against `'TOKEN=secret'` exported the value unchanged on the previous commit and redacts it on `main`. `test_extra_patterns_keep_their_configured_order` pins both orderings.

File: logfire/_internal/scrubbing.py [hunk 2]
```diff
@@ -205,13 +209,82 @@ def scrub_value(self, path: JsonPath, value: Any) -> tuple[Any, list[ScrubbedNot
...
+def _can_be_joined(pattern: str) -> bool:
+    """Whether `pattern` still means the same thing after another pattern in an alternation.
+
+    Global inline flags such as `(?s)` are only allowed at the very start of a pattern, so a pattern
+    using them can't be combined with any other. Python 3.10 only warns about this, later versions
+    raise, so turn the warning into an error to get the same answer everywhere.
+    """
+    try:
+        with warnings.catch_warnings():
+            warnings.simplefilter('error')
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply logfire/_internal/scrubbing.py]: Correct, and worse than a warning escaping — it became an exception. Fixed in the follow-up commit.

`extra_patterns=['[[a]']` works on `main`, where `re` emits `FutureWarning: Possible nested set` and the pattern still redacts. On the previous commit the blanket `simplefilter('error')` in `_can_be_joined` turned that into a raised `FutureWarning` out of `Scrubber.__init__`, so a working configuration became a hard failure at `logfire.configure()`.

`_can_be_joined` now ignores warnings and escalates `DeprecationWarning` only, which is the single category the 3.10 compatibility check needs. Ignoring the rest also stops the probe emitting a duplicate of a warning the user has already had from compiling the pattern itself. `test_extra_pattern_warning_is_not_turned_into_an_error` covers it and fails on the previous commit.

File: logfire/_internal/scrubbing.py [hunk 3]
```diff
@@ -251,7 +324,11 @@ class SpanScrubber:
     """
 
     def __init__(self, parent: Scrubber):
-        self._pattern = parent._pattern  # pyright: ignore[reportPrivateUsage]
+        patterns = parent._patterns  # pyright: ignore[reportPrivateUsage]
+        # Runs for every attribute key and value, so call the single regex directly when there's only one.
+        self._search: Callable[[str], re.Match[str] | None] = (
+            patterns[0].search if len(patterns) == 1 else partial(_leftmost_match, patterns)
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply logfire/_internal/scrubbing.py:346]: Not acting on this one, because it is not a change in this PR and the fix is a behaviour decision I would rather not make on the side.

A zero-width pattern redacts everything on `main` too:

```
# main
Scrubber(['x*']).scrub_value(('attributes', 'v'), 'harmless value')
-> ("[Scrubbed due to '']", [{'path': ('attributes', 'v'), 'matched_substring': ''}])
```

The combined alternation matches empty at position 0 there, exactly as the separated pattern does here, so this branch neither introduces nor worsens it. It is called out under "Left out deliberately" in the PR description.

Ignoring zero-width matches would change what the default configuration redacts, and there is a second option — rejecting such a pattern at `configure()` time, so the user hears about it instead of silently getting nothing scrubbed. Which of those is wanted is a product decision, so it belongs in its own issue rather than inside a group-numbering fix. I am happy to open one.

File: tests/test_secret_scrubbing.py [hunk 4]
```diff
@@ -126,6 +126,105 @@ def callback(match: logfire.ScrubMatch):
...
+    assert len(scrub_matches) == 1
+    pattern_match = scrub_matches[0].pattern_match
+    assert pattern_match.groups() == ('zzz',)
+    assert pattern_match.groupdict() == {'mine': 'zzz'}
+
+
+@pytest.mark.parametrize(
+    ('extra_pattern', 'message'),
+    [
+        ('bad[(', "unterminated character set (in scrubbing pattern 'bad[(') at position 3"),
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply tests/test_secret_scrubbing.py]: Fair, and changed in the follow-up commit.

The test now asserts only the part this module adds — `(in scrubbing pattern 'bad[(')` — plus that `exc_info.value.pos` lands inside the user's own pattern. CPython's wording and offset are no longer part of the assertion.

For the record the exact strings did hold across 3.10 to 3.14 in CI on the previous commit, so this is about not depending on that in future rather than a failure today.

File: docs/how-to-guides/scrubbing.md [hunk 5]
```diff
@@ -35,6 +35,18 @@ logfire.info(
 )
 ```
 
+Each pattern is matched on its own, so a pattern behaves exactly as it would if you passed it to
+`re.compile` yourself. In particular, a capture group — a bracketed part of a pattern, such as the
+`(\d{2})` below — belongs to the pattern it is written in, so you can refer back to it with `\1`
+without the other patterns interfering:
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply docs/how-to-guides/scrubbing.md]: Half of this is right and is changed in the follow-up commit; the other half I would rather leave out.

The flags claim was wrong: `IGNORECASE | DOTALL` are applied, which `re.compile` does not do by default, so "behaves exactly as it would if you passed it to `re.compile` yourself" overstated it. The paragraph now opens with the flags and drops that comparison.

I have not documented which patterns are compiled separately. After the ordering fix in the follow-up commit, the batching is not observable — same matches, same precedence, same callback — so it is an implementation detail, and writing it into the guide would turn a batching choice into something users could depend on. What the guide now promises is only what the SDK guarantees: the flags, and that a capture group belongs to the pattern it is written in.

File: docs/how-to-guides/scrubbing.md [hunk 6]
```diff
@@ -35,6 +35,18 @@ logfire.info(
 )
 ```
 
+Each pattern is matched on its own, so a pattern behaves exactly as it would if you passed it to
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply docs/how-to-guides/scrubbing.md]: Agreed on the scope of the claim, and changed in the follow-up commit.

"Each pattern is matched on its own" is gone. The paragraph now states the flags that are applied and that a capture group belongs to the pattern it is written in, which is what this PR actually guarantees. Tie-breaking between patterns is unchanged from `main` — leftmost match, earliest configured pattern on a tie — and the follow-up commit fixes a case where this branch had broken that.

File: tests/test_secret_scrubbing.py [hunk 7]
```diff
@@ -126,6 +126,110 @@ def callback(match: logfire.ScrubMatch):
...
+                    'code.function': 'test_scrub_with_backreference_pattern',
+                    'code.lineno': 123,
+                    'hit': "[Scrubbed due to 'bb']",
+                    'miss': 'q zz',
+                    'logfire.json_schema': '{"type":"object","properties":{"hit":{},"miss":{}}}',
+                    'logfire.scrubbed': '[{"path": ["attributes", "hit"], "matched_substring": "bb"}]',
+                },
+            }
+        ]
+    )
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply tests/test_secret_scrubbing.py:277]: Done in the follow-up commit. The test now calls `exported_spans_as_dict(parse_json_attributes=True)`, and the snapshot asserts `logfire.scrubbed` and `logfire.json_schema` as structures rather than JSON strings.

File: logfire/_internal/scrubbing.py [hunk 8]
```diff
@@ -205,13 +209,94 @@ def scrub_value(self, path: JsonPath, value: Any) -> tuple[Any, list[ScrubbedNot
...
+
+    Only neighbouring patterns are combined, so the result stays in the configured order. Where two
+    patterns match at the same position the earlier one has always won, and it still does.
+    """
+    compiled_patterns: list[re.Pattern[str]] = []
+    joinable = [_DEFAULT_PATTERN]
+
+    def flush_joinable():
+        if joinable:
+            compiled_patterns.append(re.compile('|'.join(joinable), _SCRUBBING_FLAGS))
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply logfire/_internal/scrubbing.py]: Confirmed and fixed in f5058d6, with the suggestion applied as written.

Observed before the fix, with `extra_patterns=['[[a]']`:

```
Possible nested set at position 1     scrubbing.py:219   # the user's own pattern
Possible nested set at position 279   scrubbing.py:264   # the combined pattern
```

The second one is the useless one, since position 279 is inside a string the user never wrote. The combined compile is now silent, and `test_extra_pattern_warning_is_raised_once_and_is_not_an_error` asserts the full list of warnings rather than just that one was raised, so a reappearance fails the test.

File: docs/how-to-guides/scrubbing.md [hunk 9]
```diff
@@ -35,6 +35,17 @@ logfire.info(
...
 ```
 
+Patterns are applied case-insensitively, and `.` also matches newlines. A capture group — a
+bracketed part of a pattern, such as the `(\d{2})` below — belongs to the pattern it is written in,
+so you can point back at it with `\1` without the other patterns interfering:
+
+```python
+import logfire
+
+# Redacts a repeated pair of digits, e.g. '1212', but not '1234'.
```
[the remark this answers is not in the document]
Comment (IgorKasianenko) [reply docs/how-to-guides/scrubbing.md]: Correct, and fixed in f5058d6. Checked rather than reasoned about:

```
Scrubber([r'(\d{2})\1']).scrub_value(('attributes', 'v'), '1212')       -> ('1212', [])
Scrubber([r'(\d{2})\1']).scrub_value(('attributes', 'v'), 'card 1212')  -> ("[Scrubbed due to '1212']", ...)
```

The comment now reads "Redacts a value containing a repeated pair of digits, e.g. 'card 1212', but not 'card 1234'".

I have not documented the whole-string rule itself on this page. It is pre-existing behaviour that is not specific to custom patterns — the same rule keeps a value of exactly `password` — so it belongs in its own docs change rather than in a note attached to this example.
