### ISSUE TITLE
Using StaticFiles crashes instrumentation for fastapi

### ISSUE THREAD

**Issue by tardis10** [pydantic/logfire#288]
### Description

My project uses some StaticFiles configs in FastAPI.  This broke with version ~0.43.0, version 0.42.0 works fine.

main-1  | 2024-06-29T15:00:35.805550267Z   File "/usr/local/lib/python3.12/site-packages/achernar/ltyabb/restapi/app.py", line 98, in <module>
main-1  | 2024-06-29T15:00:35.805788495Z     logfire.instrument_fastapi(app)
main-1  | 2024-06-29T15:00:35.805802763Z   File "/usr/local/lib/python3.12/site-packages/logfire/_internal/main.py", line 869, in instrument_fastapi
main-1  | 2024-06-29T15:00:35.806061535Z     return instrument_fastapi(
main-1  | 2024-06-29T15:00:35.806068786Z            ^^^^^^^^^^^^^^^^^^^
main-1  | 2024-06-29T15:00:35.806072767Z   File "/usr/local/lib/python3.12/site-packages/logfire/_internal/integrations/fastapi.py", line 76, in instrument_fastapi
main-1  | 2024-06-29T15:00:35.806252844Z     mounted_apps = find_mounted_apps(app)
main-1  | 2024-06-29T15:00:35.806317922Z                    ^^^^^^^^^^^^^^^^^^^^^^
main-1  | 2024-06-29T15:00:35.806327324Z   File "/usr/local/lib/python3.12/site-packages/logfire/_internal/integrations/fastapi.py", line 40, in find_mounted_apps
main-1  | 2024-06-29T15:00:35.806541391Z     mounted_apps += find_mounted_apps(_app)
main-1  | 2024-06-29T15:00:35.806551991Z                     ^^^^^^^^^^^^^^^^^^^^^^^
main-1  | 2024-06-29T15:00:35.806555790Z   File "/usr/local/lib/python3.12/site-packages/logfire/_internal/integrations/fastapi.py", line 36, in find_mounted_apps
main-1  | 2024-06-29T15:00:35.806558391Z     for route in app.routes:
main-1  | 2024-06-29T15:00:35.806560188Z                  ^^^^^^^^^^
main-1  | 2024-06-29T15:00:35.806561856Z AttributeError: 'StaticFiles' object has no attribute 'routes'

Appears may have been introduced with https://github.com/pydantic/logfire/pull/259

### Python, Logfire & OS Versions, related packages (not required)

```TOML
fastapi >= 0.109
logfire >= 0.43.0
```

**Comment by alexmojaki** [comment]
cc @sneakyPad

**Comment by sneakyPad** [comment]
Thanks @tardis10. I see the problem. I'll write a fix and add a test for this as well.

**Comment by tardis10** [comment]
Thanks for the quick response!

**Comment by alexmojaki** [comment]
Fixed, please `pip install -U logfire` and try again.
